# https://nimbus.guide/options.html

# Please uncomment the following line and set a suggested fee_recipient_address when running a validator.
# suggested-fee-recipient = "0x000..."

## nimbus-docker default configuration
doppelganger-detection = false
web3-url = ["http://besu:8551"]
data-dir = "/var/lib/nimbus"
jwt-secret = "/secrets/jwtsecret"
status-bar = false
non-interactive = true
subscribe-all-subnets = true
enr-auto-update = true
tcp-port = 9000
udp-port = 9000
history = "prune"

## Extra options
# nat = "extip:<INSERT_PUBLIC_IP_ADDRESS_HERE>"
# rest = true
# rest-address = "0.0.0.0"
# rest.port = 5052
# graffitti = ""
# metrics = true
# metrics-address = 0.0.0.0
# metrics-port = 8008
# keymanager = true
# keymanager-token-file = "/secrets/keymanagertoken"