data-path="/var/lib/besu"
sync-mode="X_CHECKPOINT"
data-storage-format="BONSAI"
engine-jwt-secret="/opt/besu/secrets/jwtsecret"
engine-host-allowlist=["*"]
engine-rpc-port="8551"
host-allowlist=["*"]
rpc-http-cors-origins=["*"]
rpc-http-enabled=true
rpc-http-api=["ETH","NET","WEB3"]
rpc-http-host="0.0.0.0"
rpc-http-port="8545"
nat-method="DOCKER"
#metrics-enabled=true
#metrics-host="0.0.0.0"
#metrics-port="6060"
#max-peers=25
#Xdns-enabled=true
#Xplugin-rocksdb-high-spec-enabled=true
